In [3]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("../datas/ecommerce.csv", low_memory=False)
df.head()
df.tail()
print("Rows :", df.shape[0])
print("Columns :", df.shape[1])
df.columns
df.info()
df.describe()
df.isnull().sum()
df.duplicated().sum()
df.drop_duplicates(inplace=True)
df["Order Date"].head(10)
df["Ship Date"].head(10)
numeric_columns = [
    "Sales",
    "Quantity",
    "Discount",
    "Profit",
    "Shipping Cost"
]

for col in numeric_columns:
    df[col] = (
        df[col]
        .astype(str)
        .str.replace(",", "", regex=False)
        .str.replace("$", "", regex=False)
    )

    df[col] = pd.to_numeric(df[col], errors="coerce")

Rows : 51290
Columns : 21
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order ID          51290 non-null  object
 1   Order Date        51289 non-null  object
 2   Ship Date         51290 non-null  object
 3   Aging             51289 non-null  float64
 4   Ship Mode         51290 non-null  object
 5   Product Category  51290 non-null  object
 6   Product           51290 non-null  object
 7   Sales             51290 non-null  object
 8   Quantity          51289 non-null  object
 9   Discount          51290 non-null  object
 10  Profit            51290 non-null  object
 11  Shipping Cost     51290 non-null  object
 12  Order Priority    51288 non-null  object
 13  Customer ID       51289 non-null  object
 14  Customer Name     51290 non-null  object
 15  Segment           51289 non-null  object
 16  City              51290 non-null  object
 17  State             51290 non-null  object
 18  Country           51290 non-null  object
 19  Region            51289 non-null  object
 20  Months            51290 non-null  object
dtypes: float64(1), object(20)
memory usage: 8.2+ MB

In [4]:
df.dtypes

Order ID             object
Order Date           object
Ship Date            object
Aging               float64
Ship Mode            object
Product Category     object
Product              object
Sales               float64
Quantity            float64
Discount            float64
Profit              float64
Shipping Cost       float64
Order Priority       object
Customer ID          object
Customer Name        object
Segment              object
City                 object
State                object
Country              object
Region               object
Months               object
dtype: object

In [5]:
df.isnull().sum()

Order ID            0
Order Date          1
Ship Date           0
Aging               1
Ship Mode           0
Product Category    0
Product             0
Sales               1
Quantity            2
Discount            1
Profit              0
Shipping Cost       1
Order Priority      2
Customer ID         1
Customer Name       0
Segment             1
City                0
State               0
Country             0
Region              1
Months              0
dtype: int64

In [6]:
df.describe()

,Aging,Sales,Quantity,Discount,Profit,Shipping Cost
count,51289.000000,51289.000000,51288.000000,51289.000000,51290.000000,51289.000000
mean,5.255035,156.430619,2.997368,0.029971,72.725157,7.272932
std,2.959948,65.781574,1.413446,0.014114,49.097680,4.908497
min,1.000000,33.000000,1.000000,0.010000,0.500000,0.100000
25%,3.000000,109.000000,2.000000,0.020000,25.700000,2.600000
50%,5.000000,159.000000,3.000000,0.030000,67.000000,6.700000
75%,8.000000,218.000000,4.000000,0.040000,120.600000,12.100000
max,10.500000,250.000000,5.000000,0.050000,167.500000,16.800000

In [7]:
df.isnull().sum()

Order ID            0
Order Date          1
Ship Date           0
Aging               1
Ship Mode           0
Product Category    0
Product             0
Sales               1
Quantity            2
Discount            1
Profit              0
Shipping Cost       1
Order Priority      2
Customer ID         1
Customer Name       0
Segment             1
City                0
State               0
Country             0
Region              1
Months              0
dtype: int64

In [8]:
df.dropna(inplace=True)

In [9]:
df.isnull().sum()

Order ID            0
Order Date          0
Ship Date           0
Aging               0
Ship Mode           0
Product Category    0
Product             0
Sales               0
Quantity            0
Discount            0
Profit              0
Shipping Cost       0
Order Priority      0
Customer ID         0
Customer Name       0
Segment             0
City                0
State               0
Country             0
Region              0
Months              0
dtype: int64

In [10]:
df[["Order Date", "Ship Date"]].head(10)

  Order Date Ship Date
0    11/9/15  11/17/15
1    6/30/15    7/2/15
2    12/5/15  12/13/15
3     5/9/15   5/16/15
4     7/9/15   7/18/15
5    2/25/15    3/5/15
6     4/9/15   4/10/15
7    3/30/15    4/6/15
8     2/9/15   2/16/15
9    4/21/15    5/1/15

In [11]:
df["Order Date"] = pd.to_datetime(df["Order Date"], format="%m/%d/%Y", errors="coerce")
df["Ship Date"] = pd.to_datetime(df["Ship Date"], format="%m/%d/%Y", errors="coerce")

In [12]:
df[["Order Date", "Ship Date"]].head(10)

  Order Date Ship Date
0        NaT       NaT
1        NaT       NaT
2        NaT       NaT
3        NaT       NaT
4        NaT       NaT
5        NaT       NaT
6        NaT       NaT
7        NaT       NaT
8        NaT       NaT
9        NaT       NaT

In [13]:
df["Order Date"] = pd.to_datetime(df["Order Date"], format="mixed", errors="coerce")
df["Ship Date"] = pd.to_datetime(df["Ship Date"], format="mixed", errors="coerce")

In [14]:
df[["Order Date", "Ship Date"]].head(10)

  Order Date Ship Date
0        NaT       NaT
1        NaT       NaT
2        NaT       NaT
3        NaT       NaT
4        NaT       NaT
5        NaT       NaT
6        NaT       NaT
7        NaT       NaT
8        NaT       NaT
9        NaT       NaT

In [15]:
df = pd.read_csv("../datas/ecommerce.csv", low_memory=False)
df[["Order Date", "Ship Date"]].head(10)

  Order Date Ship Date
0    11/9/15  11/17/15
1    6/30/15    7/2/15
2    12/5/15  12/13/15
3     5/9/15   5/16/15
4     7/9/15   7/18/15
5    2/25/15    3/5/15
6     4/9/15   4/10/15
7    3/30/15    4/6/15
8     2/9/15   2/16/15
9    4/21/15    5/1/15

In [16]:
df["Order Date"] = pd.to_datetime(
    df["Order Date"],
    format="%m/%d/%y"
)

df["Ship Date"] = pd.to_datetime(
    df["Ship Date"],
    format="%m/%d/%y"
)

In [17]:
print(df.dtypes)

Order ID                    object
Order Date          datetime64[ns]
Ship Date           datetime64[ns]
Aging                      float64
Ship Mode                   object
Product Category            object
Product                     object
Sales                       object
Quantity                    object
Discount                    object
Profit                      object
Shipping Cost               object
Order Priority              object
Customer ID                 object
Customer Name               object
Segment                     object
City                        object
State                       object
Country                     object
Region                      object
Months                      object
dtype: object

In [18]:
numeric_columns = [
    "Sales",
    "Quantity",
    "Discount",
    "Profit",
    "Shipping Cost"
]

for col in numeric_columns:
    df[col] = (
        df[col]
        .astype(str)
        .str.replace(",", "", regex=False)
        .str.replace("$", "", regex=False)
    )

    df[col] = pd.to_numeric(df[col], errors="coerce")

In [19]:
print(df.dtypes)

Order ID                    object
Order Date          datetime64[ns]
Ship Date           datetime64[ns]
Aging                      float64
Ship Mode                   object
Product Category            object
Product                     object
Sales                      float64
Quantity                   float64
Discount                   float64
Profit                     float64
Shipping Cost              float64
Order Priority              object
Customer ID                 object
Customer Name               object
Segment                     object
City                        object
State                       object
Country                     object
Region                      object
Months                      object
dtype: object

In [21]:
df.to_csv("../datas/cleaned_ecommerce.csv", index=False)